version: '3.8'

services:
  frontend:
    build:
      context: ./urlshortener.frontend
      dockerfile: Dockerfile
    ports:
      - "60443:60443"
    environment:
      - VITE_API_URL=https://gateway
    depends_on:
      - gateway

  backend:
    build:
      context: ./URLShortener.Backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=UrlShortenerDb;User=sa;Password=YourStrong!Password;TrustServerCertificate=True
    depends_on:
      - db

  auth:
    build:
      context: ./URLShortener.Auth
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=UrlShortenerDb;User=sa;Password=YourStrong!Password;TrustServerCertificate=True
    depends_on:
      - db

  gateway:
    build:
      context: ./URLShortener.YARP
      dockerfile: Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - backend
      - auth

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: