version: '3.8'

services:
  frontend:
    build:
      context: ./urlshortener.frontend
      dockerfile: Dockerfile
    ports:
      - "60443:60443"
    environment:
      - VITE_API_URL=https://gateway
    depends_on:
      - gateway

  backend:
    build:
      context: ./URLShortener.Backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=UrlShortenerDb;User=sa;Password=YourStrong!Password;TrustServerCertificate=True
    depends_on:
      - db

  auth:
    build:
      context: ./URLShortener.Auth
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=UrlShortenerDb;User=sa;Password=YourStrong!Password;TrustServerCertificate=True
    depends_on:
      - db

  gateway:
    build:
      context: ./URLShortener.YARP
      dockerfile: Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - backend
      - auth

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  cache:
    build:
      context: ./URLShortener.Cache
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlserver_data:
  rabbitmq_data:
  redis_data: